In [1]:
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import dataloader
import numpy

In [2]:
df = pd.read_csv("USStockMarket.csv")
df.head()

Unnamed: 0        Date  Natural_Gas_Price  Natural_Gas_Vol.  \
0           0    2/2/2024              2.079               NaN   
1           1    1/2/2024              2.050          161340.0   
2           2  31-01-2024              2.100          142860.0   
3           3  30-01-2024              2.077          139750.0   
4           4  29-01-2024              2.490            3590.0   

   Crude_oil_Price  Crude_oil_Vol.  Copper_Price  Copper_Vol. Bitcoin_Price  \
0            72.28             NaN        3.8215          NaN     43,194.70   
1            73.82        577940.0        3.8535          NaN     43,081.40   
2            75.85        344490.0        3.9060          NaN     42,580.50   
3            77.82        347240.0        3.9110          NaN     42,946.20   
4            76.78        331930.0        3.8790          NaN     43,299.80   

   Bitcoin_Vol.  ... Berkshire_Price  Berkshire_Vol. Netflix_Price  \
0         42650  ...        5,89,498           10580        564.64   
1         47690  ...        5,81,600            9780        567.51   
2         56480  ...        5,78,020            9720        564.11   
3         55130  ...        5,84,680            9750        562.85   
4         45230  ...        5,78,800           13850        575.79   

   Netflix_Vol. Amazon_Price Amazon_Vol.  Meta_Price  Meta_Vol.  Gold_Price  \
0       4030000       171.81   117220000      474.99   84710000    2,053.70   
1       3150000       159.28    66360000      394.78   25140000    2,071.10   
2       4830000       155.20    49690000      390.14   20010000    2,067.40   
3       6120000       159.00    42290000      400.06   18610000    2,050.90   
4       6880000       161.26    42840000      401.02   17790000    2,034.90   

   Gold_Vol.  
0        NaN  
1   260920.0  
2   238370.0  
3   214590.0  
4     1780.0  

[5 rows x 39 columns]

In [3]:
df.dropna(inplace=True)

In [4]:
df.tail()

Unnamed: 0      Date  Natural_Gas_Price  Natural_Gas_Vol.  \
863         863  7/8/2020              2.238          206250.0   
864         864  6/8/2020              2.165          161990.0   
865         865  5/8/2020              2.191          182430.0   
866         866  4/8/2020              2.193          230890.0   
867         867  3/8/2020              2.101          381970.0   

     Crude_oil_Price  Crude_oil_Vol.  Copper_Price  Copper_Vol. Bitcoin_Price  \
863            41.22        399000.0        2.8020        310.0     11,592.00   
864            41.95        359610.0        2.9190        290.0     11,757.10   
865            42.19        491270.0        2.9250         30.0     11,735.10   
866            41.70        451580.0        2.9030         50.0     11,184.70   
867            41.01        338330.0        2.9205         40.0     11,224.40   

     Bitcoin_Vol.  ... Berkshire_Price  Berkshire_Vol. Netflix_Price  \
863        517000  ...        3,14,334             440        494.73   
864        554850  ...        3,07,455             440        509.08   
865        570830  ...        3,05,200             560        502.11   
866        485790  ...        3,00,330             270        509.64   
867        470240  ...        2,98,800             470        498.62   

     Netflix_Vol. Amazon_Price Amazon_Vol.  Meta_Price  Meta_Vol.  Gold_Price  \
863       5910000       158.37    78720000      268.44   72770000    2,028.00   
864       3730000       161.25    78810000      265.28   45240000    2,069.40   
865       4310000       160.25    78600000      249.12   13090000    2,049.30   
866       5610000       156.94    93890000      249.83   17180000    2,021.00   
867       5880000       155.59   101490000      251.96   23130000    1,986.30   

     Gold_Vol.  
863   398130.0  
864   312760.0  
865   366380.0  
866   274420.0  
867   178750.0  

[5 rows x 39 columns]

In [5]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, format='mixed')
df.set_index('Date', inplace=True)

In [6]:
df.tail()

Unnamed: 0  Natural_Gas_Price  Natural_Gas_Vol.  Crude_oil_Price  \
Date                                                                           
2020-08-07         863              2.238          206250.0            41.22   
2020-08-06         864              2.165          161990.0            41.95   
2020-08-05         865              2.191          182430.0            42.19   
2020-08-04         866              2.193          230890.0            41.70   
2020-08-03         867              2.101          381970.0            41.01   

            Crude_oil_Vol.  Copper_Price  Copper_Vol. Bitcoin_Price  \
Date                                                                  
2020-08-07        399000.0        2.8020        310.0     11,592.00   
2020-08-06        359610.0        2.9190        290.0     11,757.10   
2020-08-05        491270.0        2.9250         30.0     11,735.10   
2020-08-04        451580.0        2.9030         50.0     11,184.70   
2020-08-03        338330.0        2.9205         40.0     11,224.40   

            Bitcoin_Vol. Platinum_Price  ...  Berkshire_Price Berkshire_Vol.  \
Date                                     ...                                   
2020-08-07        517000          977.4  ...         3,14,334            440   
2020-08-06        554850       1,020.80  ...         3,07,455            440   
2020-08-05        570830          994.9  ...         3,05,200            560   
2020-08-04        485790            961  ...         3,00,330            270   
2020-08-03        470240            938  ...         2,98,800            470   

            Netflix_Price Netflix_Vol. Amazon_Price  Amazon_Vol.  Meta_Price  \
Date                                                                           
2020-08-07         494.73      5910000       158.37     78720000      268.44   
2020-08-06         509.08      3730000       161.25     78810000      265.28   
2020-08-05         502.11      4310000       160.25     78600000      249.12   
2020-08-04         509.64      5610000       156.94     93890000      249.83   
2020-08-03         498.62      5880000       155.59    101490000      251.96   

            Meta_Vol.  Gold_Price  Gold_Vol.  
Date                                          
2020-08-07   72770000    2,028.00   398130.0  
2020-08-06   45240000    2,069.40   312760.0  
2020-08-05   13090000    2,049.30   366380.0  
2020-08-04   17180000    2,021.00   274420.0  
2020-08-03   23130000    1,986.30   178750.0  

[5 rows x 38 columns]

In [7]:
df_google = df["Google_Price"]
df_google = df_google.values

In [8]:
df_google[342]

143.61

In [9]:
stock_data = torch.FloatTensor(df_google).view(-1)

In [10]:
def create_sequence(data, seq_lenth=30):
    xs, ys = [], []
    for i in range(len(data) - seq_lenth):
        x = data[i:i+seq_lenth]
        y = data[i+seq_lenth]
        xs.append(x)
        ys.append(y)
    return torch.stack(xs), torch.stack(ys)

In [11]:
seq_lenth = 100
x, y = create_sequence(stock_data, seq_lenth)

In [12]:
x.shape, y.shape

(torch.Size([509, 100]), torch.Size([509]))

In [13]:
x, y

(tensor([[140.4200, 138.3400, 136.6500,  ..., 100.7700,  97.5600,  98.6400],
         [138.3400, 136.6500, 135.8000,  ...,  97.5600,  98.6400,  97.4200],
         [136.6500, 135.8000, 132.6000,  ...,  98.6400,  97.4200,  98.1700],
         ...,
         [ 86.1400,  87.0000,  86.3100,  ...,  74.8400,  74.9200,  75.2500],
         [ 87.0000,  86.3100,  87.6300,  ...,  74.9200,  75.2500,  73.9500],
         [ 86.3100,  87.6300,  86.8100,  ...,  75.2500,  73.9500,  73.6700]]),
 tensor([ 97.4200,  98.1700,  98.7400, 100.1400,  99.2800, 101.1400, 103.0700,
         102.8000, 102.9100, 105.0000, 104.3200, 110.8600, 110.6500, 109.4500,
         107.8500, 109.7400, 108.2200, 108.9400, 110.3400, 116.6500, 113.6900,
         113.8600, 114.2400, 117.2100, 120.1700, 119.5500, 121.7000, 122.0800,
         121.6800, 118.8400, 119.7000, 116.6300, 117.3000, 117.4700, 118.1900,
         118.0800, 115.1300, 114.8600, 116.3200, 114.2200, 113.0600, 105.0200,
         107.5100, 107.9000, 114.3400, 113.9000,

In [14]:
train_size = int(len(y) * 0.8)

x_train = x[:train_size]
y_train = y[:train_size]

y_test = y[train_size:]
x_test = x[train_size:]

In [15]:
x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.FloatTensor(y_train)
y_test = torch.FloatTensor(y_test)

In [16]:
x_train.shape, y_train.shape

(torch.Size([407, 100]), torch.Size([407]))

In [17]:
x_train = x_train.unsqueeze(0)
y_train = y_train.unsqueeze(0)

In [18]:
x_train.reshape(1, -1)
y_train.reshape(1, -1)

tensor([[ 97.4200,  98.1700,  98.7400, 100.1400,  99.2800, 101.1400, 103.0700,
         102.8000, 102.9100, 105.0000, 104.3200, 110.8600, 110.6500, 109.4500,
         107.8500, 109.7400, 108.2200, 108.9400, 110.3400, 116.6500, 113.6900,
         113.8600, 114.2400, 117.2100, 120.1700, 119.5500, 121.7000, 122.0800,
         121.6800, 118.8400, 119.7000, 116.6300, 117.3000, 117.4700, 118.1900,
         118.0800, 115.1300, 114.8600, 116.3200, 114.2200, 113.0600, 105.0200,
         107.5100, 107.9000, 114.3400, 113.9000, 113.8100, 109.0300, 111.7800,
         110.3700, 111.3500, 114.0200, 115.6800, 118.7800, 114.5700, 108.7400,
         108.9600, 111.7000, 115.8300, 117.9700, 112.2400, 111.4900, 107.1400,
         106.0300, 109.7600, 106.7200, 106.3900, 111.1600, 114.8400, 117.1900,
         117.1500, 116.8200, 114.5400, 117.6200, 113.8900, 112.3200, 105.8100,
         105.9700, 111.4900, 108.9100, 110.3800, 111.9000, 116.4700, 114.4400,
         116.0500, 112.8400, 113.6000, 114.3900, 112

In [19]:
x_train.shape, y_train.shape

(torch.Size([1, 407, 100]), torch.Size([1, 407]))

In [20]:
from zmq import device


class StockPriceLstm(nn.Module):
    def __init__(self, input_size=1, hidden_size=50, num_layer=1, output_size=1, batch_first=True):
        super(StockPriceLstm, self).__init__()

        self.lstm = nn.LSTM(input_size, hidden_size, num_layer, batch_first=batch_first)
        self.linear = nn.Linear(hidden_size, output_size)
        self.num_layer = num_layer
        self.hidden_size = hidden_size

    def forward(self, x):
        h0 = torch.zeros(self.num_layer, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layer, x.size(0), self.hidden_size).to(x.device)

        out, _ = self.lstm(x, (h0, c0))
        out = self.linear(out[:, -1, :])

        return out

In [21]:
lstm_model = StockPriceLstm(input_size=seq_lenth)
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=0.01)

In [22]:
epochs = 2000
for epoch in range(epochs):
    for x_batch, y_batch in zip(x_train, y_train):
        y_pred = lstm_model(x_train)
        loss = loss_fn(y_pred, y_train)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 100 == 0:
            print(f"Epoch: {epoch}, Loss: {loss.item()}")

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1, 407])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch: 0, Loss: 15667.4326171875
Epoch: 100, Loss: 12465.9921875
Epoch: 200, Loss: 9885.71484375
Epoch: 300, Loss: 7743.06005859375
Epoch: 400, Loss: 5986.83056640625
Epoch: 500, Loss: 4568.3125
Epoch: 600, Loss: 3441.15478515625
Epoch: 700, Loss: 2561.596923828125
Epoch: 800, Loss: 1888.837890625
Epoch: 900, Loss: 1385.4361572265625
Epoch: 1000, Loss: 1017.6907958984375
Epoch: 1100, Loss: 755.9595336914062
Epoch: 1200, Loss: 574.8526611328125
Epoch: 1300, Loss: 453.2630615234375
Epoch: 1400, Loss: 374.2242431640625
Epoch: 1500, Loss: 324.5726623535156
Epoch: 1600, Loss: 294.490234375
Epoch: 1700, Loss: 276.9443054199219
Epoch: 1800, Loss: 267.11041259765625
Epoch: 1900, Loss: 261.8247985839844
