In [1]:
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
df = pd.read_csv("BostonHousing.csv")
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [3]:
x = df.drop('medv', axis=1)
y = df['medv']

In [4]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [5]:
x = x.values

In [6]:
y = y.values

In [7]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [8]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
x.shape

(506, 13)

In [10]:
x_train = x[0:405, :]
x_test = x[406::, :]

In [11]:
x_train.shape, x_test.shape

((405, 13), (100, 13))

In [12]:
y.shape

(506,)

In [13]:
y_train = y[0:405]
y_test = y[406::]

In [14]:
y_train.shape, y_test.shape

((405,), (100,))

In [15]:
x_test = torch.FloatTensor(x_test)
x_train = torch.FloatTensor(x_train)
y_test = torch.FloatTensor(y_test)
y_train = torch.FloatTensor(y_train)

In [16]:
class LinearRegressionModel(nn.Module):
    def __init__(self, in_features = 13, out_features=1):
        super().__init__()
        self.func = nn.Linear(in_features, out_features)

    def forward(self, x):
        out = self.func(x)

        return out

In [17]:
model = LinearRegressionModel()

In [18]:
model.parameters()

<generator object Module.parameters at 0x00000172DE9E9540>

In [19]:
loss_func = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [46]:
epochs = 1000
losses = []

for epoch in range(epochs):
    y_pred = model.forward(x_train)
    
    loss = loss_func(y_pred, y_train)

    losses.append(loss.detach())

    if (epoch+1)%100 == 0:
        print(f"Epoch: {epoch}, loss: {loss}")

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([405])) that is different to the input size (torch.Size([405, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch: 99, loss: 86.13816833496094
Epoch: 199, loss: 86.13518524169922
Epoch: 299, loss: 86.13306427001953
Epoch: 399, loss: 86.1319580078125
Epoch: 499, loss: 86.12906646728516
Epoch: 599, loss: 86.12701416015625
Epoch: 699, loss: 86.12591552734375
Epoch: 799, loss: 86.12313842773438
Epoch: 899, loss: 86.12115478515625
Epoch: 999, loss: 86.119384765625


In [30]:
y_pred.shape, y_train.shape

(torch.Size([405, 1]), torch.Size([405]))

In [49]:
with torch.no_grad():
    y_eval = model.forward(x_test)
    loss = loss_func(y_eval, y_test)
    print(loss)
    for i in range(len(y_eval)):
        print(f"y_eval: {y_eval[i].item()}, y_test: {y_test[i]}, diff: {y_eval[i].item() - y_test[i]}.")

tensor(83.3255)
y_eval: 23.135038375854492, y_test: 11.899999618530273, diff: 11.235038757324219.
y_eval: 23.479755401611328, y_test: 27.899999618530273, diff: -4.420244216918945.
y_eval: 23.43877410888672, y_test: 17.200000762939453, diff: 6.238773345947266.
y_eval: 23.25578498840332, y_test: 27.5, diff: -4.24421501159668.
y_eval: 21.564077377319336, y_test: 15.0, diff: 6.564077377319336.
y_eval: 22.56290626525879, y_test: 17.200000762939453, diff: 5.362905502319336.
y_eval: 21.827465057373047, y_test: 17.899999618530273, diff: 3.9274654388427734.
y_eval: 22.535839080810547, y_test: 16.299999237060547, diff: 6.23583984375.
y_eval: 22.518539428710938, y_test: 7.0, diff: 15.518539428710938.
y_eval: 23.063112258911133, y_test: 7.199999809265137, diff: 15.863112449645996.
y_eval: 23.19236183166504, y_test: 7.5, diff: 15.692361831665039.
y_eval: 22.882774353027344, y_test: 10.399999618530273, diff: 12.48277473449707.
y_eval: 22.36058235168457, y_test: 8.800000190734863, diff: 13.5605821609

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [32]:
model.state_dict()

OrderedDict([('func.weight',
              tensor([[-4.8281e-03,  5.8852e-04, -1.1987e-02,  6.7038e-03,  5.9556e+00,
                        5.4932e-01, -3.6237e-03,  1.4828e-01, -4.4572e-02,  8.4486e-04,
                        1.4910e-01,  4.9364e-03,  2.5546e-02]])),
             ('func.bias', tensor([12.3557]))])

In [33]:
def ridge_loss(output, target, model, alpha):
    mse_loss = nn.MSELoss()(output, target)
    l2_reg = torch.tensor(0.)
    for param in model.parameters():
        l2_reg += torch.norm(param)
    return mse_loss + alpha + l2_reg

In [34]:
def lasso_loss(output, target, model, alpha):
    mse_loss = nn.MSELoss()(output, target)
    l1_reg = torch.tensor(0.)
    for param in model.parameters():
        l1_reg += torch.sum(torch.abs(param))
    return mse_loss + alpha + l1_reg

In [35]:
optimizer2 = torch.optim.SGD(model.parameters(), lr = 0.01)

In [36]:
model_ridge = LinearRegressionModel()

In [37]:
epochs = 1000
for i in range(epochs):
    y_pred_ridge = model_ridge.forward(x_train)

    loss_ridge = ridge_loss(y_pred_ridge, y_train, model_ridge, 0.1)

    if (i+1)%100 == 0:
        print(f"Epoch: {i+1}, loss: {loss_ridge}")

    optimizer.zero_grad()
    loss_ridge.backward()
    optimizer2.step()


Epoch: 100, loss: 26169.431640625
Epoch: 200, loss: 26169.431640625
Epoch: 300, loss: 26169.431640625
Epoch: 400, loss: 26169.431640625
Epoch: 500, loss: 26169.431640625
Epoch: 600, loss: 26169.431640625
Epoch: 700, loss: 26169.431640625
Epoch: 800, loss: 26169.431640625
Epoch: 900, loss: 26169.431640625
Epoch: 1000, loss: 26169.431640625


In [42]:
model_ridge.state_dict()

OrderedDict([('func.weight',
              tensor([[-0.0783, -0.1301,  0.0027, -0.1568,  0.2461, -0.2153, -0.0646, -0.0086,
                        0.0058, -0.0700, -0.1462, -0.2736,  0.1537]])),
             ('func.bias', tensor([0.1697]))])

In [43]:
model.state_dict()

OrderedDict([('func.weight',
              tensor([[-4.8281e-03,  5.8852e-04, -1.1987e-02,  6.7038e-03,  5.9556e+00,
                        5.4932e-01, -3.6237e-03,  1.4828e-01, -4.4572e-02,  8.4486e-04,
                        1.4910e-01,  4.9364e-03,  2.5546e-02]])),
             ('func.bias', tensor([12.3557]))])

In [48]:
model.state_dict()

OrderedDict([('func.weight',
              tensor([[-4.1477e-03,  5.7454e-04, -1.1246e-02,  5.5110e-03,  5.4124e+00,
                        4.8580e-01, -3.2924e-03,  1.3298e-01, -3.9733e-02,  7.5120e-04,
                        1.3341e-01,  4.4364e-03,  2.2377e-02]])),
             ('func.bias', tensor([13.6139]))])