In [49]:
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

In [50]:
df = pd.read_csv("BostonHousing.csv")
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [51]:
x = df.drop('medv', axis=1)
y = df['medv']

In [52]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [53]:
x = x.values

In [54]:
y = y.values

In [55]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [56]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [57]:
x.shape

(506, 13)

In [58]:
x_train = x[0:405, :]
x_test = x[406::, :]

In [59]:
x_train.shape, x_test.shape

((405, 13), (100, 13))

In [60]:
y.shape

(506,)

In [61]:
y_train = y[0:405]
y_test = y[406::]

In [62]:
y_train.shape, y_test.shape

((405,), (100,))

In [63]:
x_test = torch.FloatTensor(x_test)
x_train = torch.FloatTensor(x_train)
y_test = torch.FloatTensor(y_test)
y_train = torch.FloatTensor(y_train)

In [96]:
class LinearRegressionModel(nn.Module):
    def __init__(self, in_features = 13, out_features=1):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(in_features, out_features)

    def forward(self, x):
        return self.linear(x)

In [97]:
model = LinearRegressionModel()

In [98]:
model.parameters()

<generator object Module.parameters at 0x0000018C59757680>

In [99]:
loss_func = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [100]:
epochs = 1000
losses = []

for epoch in range(epochs):
    y_pred = model.forward(x_train)
    
    loss = loss_func(y_pred, y_train)

    losses.append(loss.detach())

    if (epoch+1)%100 == 0:
        print(f"Epoch: {epoch}, loss: {loss}")

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([405])) that is different to the input size (torch.Size([405, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch: 99, loss: 131.0185089111328
Epoch: 199, loss: 104.82685089111328
Epoch: 299, loss: 96.90785217285156
Epoch: 399, loss: 92.9059829711914
Epoch: 499, loss: 90.9559326171875
Epoch: 599, loss: 90.01603698730469
Epoch: 699, loss: 89.50554656982422
Epoch: 799, loss: 89.1714859008789
Epoch: 899, loss: 88.92125701904297
Epoch: 999, loss: 88.72219848632812


In [101]:
y_pred.shape, y_train.shape

(torch.Size([405, 1]), torch.Size([405]))

In [102]:
with torch.no_grad():
    y_eval = model.forward(x_test)
    loss = loss_func(y_eval, y_test)
    print(loss)
    for i in range(len(y_eval)):
        print(f"y_eval: {y_eval[i].item()}, y_test: {y_test[i]}, diff: {y_eval[i].item() - y_test[i]}.")

tensor(81.5856)
y_eval: 23.86878776550293, y_test: 11.899999618530273, diff: 11.968788146972656.
y_eval: 23.81342124938965, y_test: 27.899999618530273, diff: -4.086578369140625.
y_eval: 23.185016632080078, y_test: 17.200000762939453, diff: 5.985015869140625.
y_eval: 18.756717681884766, y_test: 27.5, diff: -8.743282318115234.
y_eval: 10.381624221801758, y_test: 15.0, diff: -4.618375778198242.
y_eval: 13.72343635559082, y_test: 17.200000762939453, diff: -3.476564407348633.
y_eval: 12.274092674255371, y_test: 17.899999618530273, diff: -5.625906944274902.
y_eval: 18.472070693969727, y_test: 16.299999237060547, diff: 2.1720714569091797.
y_eval: 12.748592376708984, y_test: 7.0, diff: 5.748592376708984.
y_eval: 13.080942153930664, y_test: 7.199999809265137, diff: 5.880942344665527.
y_eval: 13.203947067260742, y_test: 7.5, diff: 5.703947067260742.
y_eval: 15.362825393676758, y_test: 10.399999618530273, diff: 4.962825775146484.
y_eval: 9.576042175292969, y_test: 8.800000190734863, diff: 0.77604

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [103]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.0562,  0.0157,  0.1136,  0.0469, -0.0328,  0.3560,  0.0294,  0.2753,
                        0.0382,  0.0006,  0.2109,  0.0345, -0.0191]])),
             ('linear.bias', tensor([0.3894]))])

In [104]:
def ridge_loss(output, target, modl, alpha):
    mse_loss = nn.MSELoss()(output, target)
    l2_reg = torch.tensor(0.)
    for param in modl.parameters():
        l2_reg += torch.norm(param)
    return l2_reg + mse_loss + alpha

model_ridge = LinearRegressionModel()
optimizer_ridge = torch.optim.SGD(model_ridge.parameters(), lr = 0.01)

In [105]:
def lasso_loss(output, target, modl, alpha):
    mse_loss = nn.MSELoss()(output, target)
    l1_reg = torch.tensor(0.)
    for param in modl.parameters():
        l1_reg += torch.sum(torch.abs(param))
    return mse_loss + alpha + l1_reg

model_lasso = LinearRegressionModel()
optimizer_lasso = torch.optim.SGD(model_lasso.parameters(), lr=0.01)

In [106]:
epochs = 1000
for i in range(epochs):
    y_pred_ridge = model_ridge(x_train)

    loss_ridge = ridge_loss(y_pred_ridge, y_train, model_ridge, 0.1)

    if (i+1) % 100 == 0:
        print(f"Epoch: {i+1}, loss: {loss_ridge.item()}")

    optimizer_ridge.zero_grad()
    loss_ridge.backward()
    optimizer_ridge.step()


Epoch: 100, loss: nan
Epoch: 200, loss: nan
Epoch: 300, loss: nan
Epoch: 400, loss: nan
Epoch: 500, loss: nan
Epoch: 600, loss: nan
Epoch: 700, loss: nan
Epoch: 800, loss: nan
Epoch: 900, loss: nan
Epoch: 1000, loss: nan


In [107]:
epochs = 1000
for epoch in range(epochs):
    model_lasso.train()
    y_pred = model_lasso(x_train)

    loss_lasso = lasso_loss(y_pred, y_train, model_lasso, 0.1)

    if epoch % 100 == 0:
        print(f"Epoch: {epoch}, loss: {loss_lasso.item()}")

    optimizer_lasso.zero_grad()
    loss_lasso.backward()
    optimizer_lasso.step()


Epoch: 0, loss: 353.5484619140625
Epoch: 100, loss: nan
Epoch: 200, loss: nan
Epoch: 300, loss: nan
Epoch: 400, loss: nan
Epoch: 500, loss: nan
Epoch: 600, loss: nan
Epoch: 700, loss: nan
Epoch: 800, loss: nan
Epoch: 900, loss: nan


In [109]:
coefficients_ridge = model_ridge.linear.weight.detach().numpy().flatten()
features = df.columns[:-1]  # All feature names

importance_df_ridge = pd.DataFrame({'Feature': features, 'Coefficient': coefficients_ridge})
importance_df_ridge = importance_df_ridge.sort_values(by='Coefficient', ascending=False)

print(importance_df_ridge)

    Feature  Coefficient
0      crim          NaN
1        zn          NaN
2     indus          NaN
3      chas          NaN
4       nox          NaN
5        rm          NaN
6       age          NaN
7       dis          NaN
8       rad          NaN
9       tax          NaN
10  ptratio          NaN
11        b          NaN
12    lstat          NaN


In [110]:
for param in model_lasso.parameters():
    print(param)

Parameter containing:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
       requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
